name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  run-steps:
    uses: waddafunk/make-pipelines/.github/workflows/CI.yml@main
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]'
      os: '["ubuntu-latest"]'